name = "SwapAndAddFV"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["SwapAndAddFV"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.header = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.34.1"

[[lean_lib]]
name = "SwapAndAddFV"

[[lean_exe]]
name = "vectors"
root = "Vectors"
